name: Test

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/actions/install-deps

      - name: Build libraries
        run: |
          npm run build:libs
          git diff --exit-code

      - name: Check TypeScript
        run: npm run check

      - name: Lint
        run: npm run lint
        # TODO: uncomment this step after testing
      #      - name: Run unit test with coverage
      #        run: npx jest --coverage --verbose

      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage/clover.xml
          verbose: true # optional (default = false)

  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    needs: unit-test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: ./.github/actions/install-deps

      - name: Prepare repository
        run: git fetch --unshallow --prune --tags

      - name: Unset header
        run: git config --local --unset http.https://github.com/.extraheader

      # TODO: remove this step after testing
      - name: Restore build extension
        uses: actions/cache@v3
        id: restore_build_extension
        with:
          path: 'packages/extension-chrome/nexus.zip'
          key: ${{ runner.os }}-${{ hashFiles('packages/*/src') }}

      - name: Build extension
        if: steps.restore_build_extension.outputs.cache-hit != 'true'
        run: |
          npm run build:libs
          npm run build:extension-chrome
          npm run -w @nexus-wallet/extension-chrome zip

      - name: Create Release
        run: npx auto shipit -vv
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
